### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by pageofthailand** [fbsamples/messenger-platform-samples#72]
`TypeError: Cannot read property 'forEach' of undefined
 at /root/node/app.js:95:26
at Array.forEach (native)
at /root/node/app.js:90:16
at Layer.handle [as handle_request] (/root/node/node_modules/express/lib/router/layer.js:95:5)
 at next (/root/node/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/root/node/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/root/node/node_modules/express/lib/router/layer.js:95:5)
 at /root/node/node_modules/express/lib/router/index.js:281:22
 at Function.process_params (/root/node/node_modules/express/lib/router/index.js:335:12)
at next (/root/node/node_modules/express/lib/router/index.js:275:10)
`

**Comment by amuramoto** [comment]
Your calling forEach on an undefined object, but this cannot be debugged with just the error message. Please post a link to your code and some details about what returned this error.

**Comment by pageofthailand** [comment]
![dfgdfgdgdgdgdfgd](https://user-images.githubusercontent.com/32870425/32649188-bd159ce2-c62b-11e7-88ca-d10bac13270e.png)

**Comment by amuramoto** [comment]
Can you put a `console.log(data)` under var data = req.body; and provide the output? 

The issue is that pageEntry.messaging is undefined, but this can't be debugged without knowing what's being received in the body of the webhook event.

**Comment by amuramoto** [comment]
Closing this since there has been no response for over a week.
